import { CommunityPost, CommunityComment } from '@/types/community';

export const INITIAL_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'post-1',
    user_id: 'user-vn-01',
    user_name: '호치민호랑이',
    user_country: 'VN',
    user_flag: '🇻🇳',
    category: 'friends',
    title: '주말에 평택에서 같이 베트남 쌀국수 먹고 한국어 공부할 친구 구해요! 🍜',
    content: '안녕하세요! 한국에 온 지 8개월 된 호랑이라고 합니다. 주말마다 혼자 방에만 있으니까 너무 외로워서 글 올려요. 이번 주 일요일 오후에 같이 맛있는 거 먹고 서로 언어 교환(베트남어 ↔ 한국어) 하실 동네 친구분 계신가요? 국적 상관없이 편하게 댓글 남겨주세요!',
    images: [
      'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 평택시',
    industrial_zone: 'pyeongtaek',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '주말에 평택에서 같이 베트남 쌀국수 먹고 한국어 공부할 친구 구해요! 🍜',
        content: '안녕하세요! 한국에 온 지 8개월 된 호랑이라고 합니다. 주말마다 혼자 방에만 있으니까 너무 외로워서 글 올려요. 이번 주 일요일 오후에 같이 맛있는 거 먹고 서로 언어 교환(베트남어 ↔ 한국어) 하실 동네 친구분 계신가요? 국적 상관없이 편하게 댓글 남겨주세요!',
      },
    },
    like_count: 14,
    cheer_count: 8,
    comment_count: 4,
    view_count: 128,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-2',
    user_id: 'user-np-02',
    user_name: '히말라야미소',
    user_country: 'NP',
    user_flag: '🇳🇵',
    category: 'daily_healing',
    title: '오늘 고향에 있는 딸아이와 영상통화 했는데 너무 보고 싶네요.. 힘내봅니다 ☕',
    content: '퇴근하고 네팔에 있는 가족들과 통화했습니다. 5살 딸아이가 아빠 언제 오냐고 묻는데 눈물이 핑 돌더라고요. 가족들 생각하면서 오늘도 야근 열심히 버텼습니다. 한국에서 일하시는 모든 외국인 친구분들, 우리 모두 힘내요!',
    images: [
      'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 안산시',
    industrial_zone: 'ansan',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '오늘 고향에 있는 딸아이와 영상통화 했는데 너무 보고 싶네요.. 힘내봅니다 ☕',
        content: '퇴근하고 네팔에 있는 가족들과 통화했습니다. 5살 딸아이가 아빠 언제 오냐고 묻는데 눈물이 핑 돌더라고요. 가족들 생각하면서 오늘도 야근 열심히 버텼습니다. 한국에서 일하시는 모든 외국인 친구분들, 우리 모두 힘내요!',
      },
    },
    like_count: 32,
    cheer_count: 27,
    comment_count: 6,
    view_count: 245,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-3',
    user_id: 'user-mn-03',
    user_name: '초원의달림이',
    user_country: 'MN',
    user_flag: '🇲🇳',
    category: 'qna',
    title: '질문: 노란색 종량제 쓰레기봉투는 어디서 사나요? 편의점에서도 파나요?',
    content: '원룸으로 이사 온 지 3일 됐는데 일반 쓰레기는 어떤 봉투에 버려야 하나요? 편의점 가서 종량제 봉투 달라고 하면 주나요?',
    images: [
      'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 화성시',
    industrial_zone: 'hwaseong',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '질문: 노란색 종량제 쓰레기봉투는 어디서 사나요? 편의점에서도 파나요?',
        content: '원룸으로 이사 온 지 3일 됐는데 일반 쓰레기는 어떤 봉투에 버려야 하나요? 편의점 가서 종량제 봉투 달라고 하면 주나요?',
      },
    },
    like_count: 5,
    cheer_count: 2,
    comment_count: 3,
    view_count: 89,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-4',
    user_id: 'user-th-04',
    user_name: '방콕라이더',
    user_country: 'TH',
    user_flag: '🇹🇭',
    category: 'food_mart',
    title: '화성 향남 근처에 진짜 태국 향신료랑 두리안 파는 아시안 마트 추천합니다 🍲',
    content: '향남읍 행정복지센터 건너편에 새로 생긴 아시안 마트 가봤는데 똠얌 페이스트랑 피쉬소스, 신선한 야채가 다 있네요! 사장님도 엄청 친절하셔서 추천드려요.',
    images: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 화성시',
    industrial_zone: 'hwaseong',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '화성 향남 근처에 진짜 태국 향신료랑 두리안 파는 아시안 마트 추천합니다 🍲',
        content: '향남읍 행정복지센터 건너편에 새로 생긴 아시안 마트 가봤는데 똠얌 페이스트랑 피쉬소스, 신선한 야채가 다 있네요! 사장님도 엄청 친절하셔서 추천드려요.',
      },
    },
    like_count: 19,
    cheer_count: 4,
    comment_count: 5,
    view_count: 172,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 14).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-5',
    user_id: 'user-uz-05',
    user_name: '타슈켄트친구',
    user_country: 'UZ',
    user_flag: '🇺🇿',
    category: 'visa',
    title: 'E-9 비자 근무처 변경할 때 고용센터에 필요한 서류 정리해드려요! 📄',
    content: '얼마 전에 사업장 변경 신청하면서 직접 준비했던 서류들 공유합니다. 1) 사업장변경신청서, 2) 외국인등록증 앞뒤 복사본, 3) 표준근로계약서 사본, 4) 이전 회사 퇴사합의서(있을 경우). 고용센터 가실 때 아침 일찍 가시면 대기시간 없이 10분 만에 접수 가능해요! 궁금한 점 댓글 주세요.',
    images: [
      'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 화성시',
    industrial_zone: 'hwaseong',
    source_lang: 'ko',
    translations: {
      ko: {
        title: 'E-9 비자 근무처 변경할 때 고용센터에 필요한 서류 정리해드려요! 📄',
        content: '얼마 전에 사업장 변경 신청하면서 직접 준비했던 서류들 공유합니다. 1) 사업장변경신청서, 2) 외국인등록증 앞뒤 복사본, 3) 표준근로계약서 사본, 4) 이전 회사 퇴사합의서(있을 경우). 고용센터 가실 때 아침 일찍 가시면 대기시간 없이 10분 만에 접수 가능해요! 궁금한 점 댓글 주세요.',
      },
    },
    like_count: 28,
    cheer_count: 12,
    comment_count: 7,
    view_count: 310,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 18).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-6',
    user_id: 'user-kh-06',
    user_name: '프놈펜스마일',
    user_country: 'KH',
    user_flag: '🇰🇭',
    category: 'friends',
    title: '천안 신부동 근처 주말에 같이 배드민턴이나 풋살 찰 외국인 친구들 모여요 🏸',
    content: '주말마다 기숙사에만 있으니 몸도 찌뿌둥하고 답답해서 글 올립니다. 천안종합운동장이나 신부동 근처 체육공원에서 가볍게 배드민턴 치거나 풋살 하실 분 계신가요? 실력 상관없이 땀 흘리면서 친목 다져요! 라켓 없으시면 빌려드립니다.',
    images: [
      'https://images.unsplash.com/photo-1526676037777-05a232554f77?w=800&auto=format&fit=crop&q=80',
    ],
    region: '충남 천안시',
    industrial_zone: 'cheonan',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '천안 신부동 근처 주말에 같이 배드민턴이나 풋살 찰 외국인 친구들 모여요 🏸',
        content: '주말마다 기숙사에만 있으니 몸도 찌뿌둥하고 답답해서 글 올립니다. 천안종합운동장이나 신부동 근처 체육공원에서 가볍게 배드민턴 치거나 풋살 하실 분 계신가요? 실력 상관없이 땀 흘리면서 친목 다져요! 라켓 없으시면 빌려드립니다.',
      },
    },
    like_count: 16,
    cheer_count: 5,
    comment_count: 4,
    view_count: 142,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 22).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-7',
    user_id: 'user-id-07',
    user_name: '자바섬형제',
    user_country: 'ID',
    user_flag: '🇮🇩',
    category: 'food_mart',
    title: '정왕동 시화공단 쪽에 인도네시아 삼발소스랑 할랄 식재료 파는 곳 어디가 제일 신선한가요? 🌶️',
    content: '시화공단으로 이직해 온 지 2주 됐습니다. 기숙사에서 삼발 테라시랑 나시고렝 직접 해먹으려고 하는데 정왕시장 근처 아시안 마트 중에 할랄 닭고기랑 향신료 신선하게 파는 곳 추천 부탁드려요!',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 시흥시',
    industrial_zone: 'sihwa',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '정왕동 시화공단 쪽에 인도네시아 삼발소스랑 할랄 식재료 파는 곳 어디가 제일 신선한가요? 🌶️',
        content: '시화공단으로 이직해 온 지 2주 됐습니다. 기숙사에서 삼발 테라시랑 나시고렝 직접 해먹으려고 하는데 정왕시장 근처 아시안 마트 중에 할랄 닭고기랑 향신료 신선하게 파는 곳 추천 부탁드려요!',
      },
    },
    like_count: 11,
    cheer_count: 3,
    comment_count: 5,
    view_count: 98,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 26).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-8',
    user_id: 'user-mm-08',
    user_name: '양곤의별',
    user_country: 'MM',
    user_flag: '🇲🇲',
    category: 'daily_healing',
    title: '첫 월급 받아서 고향 부모님께 송금해 드렸습니다. 뿌듯하고 가슴이 벅차네요 💌',
    content: '한국에 입국해서 3교대 공장 일 시작한 지 꼭 한 달 만에 첫 월급 받았습니다. 월급 받자마자 부모님 생활비랑 동생 학비 먼저 송금해 드렸는데, 어머니께서 전화로 눈물 흘리시면서 고맙다고 하시네요. 타국에서 힘들지만 이 맛에 버티나 봅니다. 모두 건강 챙기면서 일하세요!',
    images: [
      'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&auto=format&fit=crop&q=80',
    ],
    region: '인천 남동구',
    industrial_zone: 'namdong',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '첫 월급 받아서 고향 부모님께 송금해 드렸습니다. 뿌듯하고 가슴이 벅차네요 💌',
        content: '한국에 입국해서 3교대 공장 일 시작한 지 꼭 한 달 만에 첫 월급 받았습니다. 월급 받자마자 부모님 생활비랑 동생 학비 먼저 송금해 드렸는데, 어머니께서 전화로 눈물 흘리시면서 고맙다고 하시네요. 타국에서 힘들지만 이 맛에 버티나 봅니다. 모두 건강 챙기면서 일하세요!',
      },
    },
    like_count: 45,
    cheer_count: 38,
    comment_count: 9,
    view_count: 412,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 30).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-9',
    user_id: 'user-cn-09',
    user_name: '안산판다',
    user_country: 'CN',
    user_flag: '🇨🇳',
    category: 'qna',
    title: '질문: 건강보험 피부양자 등록할 때 가족관계증명서 아포스티유 공증 꼭 필요한가요? 🤔',
    content: 'F-4 비자로 회사 다니고 있는데 고향에 계신 부모님을 피부양자로 등록하려고 합니다. 국민건강보험공단 지사 방문 시 중국 가족관계증명서 원본에 외교부 인증 및 한국어 번역공증이 필수인가요? 최근에 등록해보신 선배님들 조언 부탁드립니다.',
    images: [
      'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 안산시',
    industrial_zone: 'ansan',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '질문: 건강보험 피부양자 등록할 때 가족관계증명서 아포스티유 공증 꼭 필요한가요? 🤔',
        content: 'F-4 비자로 회사 다니고 있는데 고향에 계신 부모님을 피부양자로 등록하려고 합니다. 국민건강보험공단 지사 방문 시 중국 가족관계증명서 원본에 외교부 인증 및 한국어 번역공증이 필수인가요? 최근에 등록해보신 선배님들 조언 부탁드립니다.',
      },
    },
    like_count: 8,
    cheer_count: 3,
    comment_count: 4,
    view_count: 115,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 35).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-10',
    user_id: 'user-ph-10',
    user_name: '마닐라프렌드',
    user_country: 'PH',
    user_flag: '🇵🇭',
    category: 'friends',
    title: '수원역 근처에서 주말에 따뜻하게 커피 마시면서 영어-한국어 대화 나눌 친구 구해요 ☕',
    content: '안녕하세요! 수원 제조업체에서 일하는 마크입니다. 한국 온 지 1년 정도 되었는데 한국어 회화 실력을 더 늘리고 싶어요. 주말에 수원역 AK플라자나 인계동 카페에서 편하게 수다 떨면서 한국어 가르쳐주실 한국 친구나 영어 교환하고 싶으신 분 언제든 연락주세요!',
    images: [
      'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 수원시',
    industrial_zone: 'suwon',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '수원역 근처에서 주말에 따뜻하게 커피 마시면서 영어-한국어 대화 나눌 친구 구해요 ☕',
        content: '안녕하세요! 수원 제조업체에서 일하는 마크입니다. 한국 온 지 1년 정도 되었는데 한국어 회화 실력을 더 늘리고 싶어요. 주말에 수원역 AK플라자나 인계동 카페에서 편하게 수다 떨면서 한국어 가르쳐주실 한국 친구나 영어 교환하고 싶으신 분 언제든 연락주세요!',
      },
    },
    like_count: 21,
    cheer_count: 6,
    comment_count: 5,
    view_count: 180,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 40).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-11',
    user_id: 'user-lk-11',
    user_name: '실론티러버',
    user_country: 'LK',
    user_flag: '🇱🇰',
    category: 'tips',
    title: 'KTRS에서 연말정산 외국인 세금환급 신청했는데 168만원 돌려받았습니다! 후기 공유해요 🎉',
    content: '외국인 근로자는 세금 혜택 잘 모르면 그냥 넘어가는 경우가 많은데, KTRS 간편 세금환급 조회해보니 지난 3년간 냈던 소득세 중에 168만원이나 환급 대상이더라고요. 국세청에서 계좌로 입금된 후에 수수료 내는 후불제라 안심하고 신청했습니다. 안 해보신 분들 꼭 조회해보세요!',
    images: [
      'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경남 김해시',
    industrial_zone: 'gimhae',
    source_lang: 'ko',
    translations: {
      ko: {
        title: 'KTRS에서 연말정산 외국인 세금환급 신청했는데 168만원 돌려받았습니다! 후기 공유해요 🎉',
        content: '외국인 근로자는 세금 혜택 잘 모르면 그냥 넘어가는 경우가 많은데, KTRS 간편 세금환급 조회해보니 지난 3년간 냈던 소득세 중에 168만원이나 환급 대상이더라고요. 국세청에서 계좌로 입금된 후에 수수료 내는 후불제라 안심하고 신청했습니다. 안 해보신 분들 꼭 조회해보세요!',
      },
    },
    like_count: 36,
    cheer_count: 19,
    comment_count: 8,
    view_count: 365,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 46).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-12',
    user_id: 'user-bd-12',
    user_name: '다카나눔이',
    user_country: 'BD',
    user_flag: '🇧🇩',
    category: 'tips',
    title: '기숙사 이사하면서 깨끗한 전기포트랑 밥솥 무료나눔합니다! 필요하신 분 댓글 주세요 🎁',
    content: '이번 주말에 다른 공장 기숙사로 이사하게 되어 짐 정리 중입니다. 6개월 정도 깨끗하게 사용한 3인용 쿠쿠 전기밥솥과 테팔 무선전기포트 무료로 나눔합니다. 청주 오창읍 산업단지 기숙사 앞으로 직접 가지러 오실 수 있는 분께 먼저 드릴게요!',
    images: [
      'https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=800&auto=format&fit=crop&q=80',
    ],
    region: '충북 청주시',
    industrial_zone: 'cheongju',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '기숙사 이사하면서 깨끗한 전기포트랑 밥솥 무료나눔합니다! 필요하신 분 댓글 주세요 🎁',
        content: '이번 주말에 다른 공장 기숙사로 이사하게 되어 짐 정리 중입니다. 6개월 정도 깨끗하게 사용한 3인용 쿠쿠 전기밥솥과 테팔 무선전기포트 무료로 나눔합니다. 청주 오창읍 산업단지 기숙사 앞으로 직접 가지러 오실 수 있는 분께 먼저 드릴게요!',
      },
    },
    like_count: 22,
    cheer_count: 14,
    comment_count: 6,
    view_count: 195,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 52).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-13',
    user_id: 'user-kz-13',
    user_name: '알마티바람',
    user_country: 'KZ',
    user_flag: '🇰🇿',
    category: 'daily_healing',
    title: '한국의 사계절 중 봄 벚꽃이 정말 아름답네요. 주말에 공원 산책 추천합니다 🌸',
    content: '카자흐스탄에서는 볼 수 없었던 핑크빛 벚꽃길을 보니까 마음이 참 평화로워집니다. 퇴근길에 회사 근처 호수공원 걸으면서 사진 찍어봤어요. 다들 바쁘고 힘든 일상이지만 주변 풍경도 한 번씩 둘러보시면서 힐링하세요!',
    images: [
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 화성시',
    industrial_zone: 'hwaseong',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '한국의 사계절 중 봄 벚꽃이 정말 아름답네요. 주말에 공원 산책 추천합니다 🌸',
        content: '카자흐스탄에서는 볼 수 없었던 핑크빛 벚꽃길을 보니까 마음이 참 평화로워집니다. 퇴근길에 회사 근처 호수공원 걸으면서 사진 찍어봤어요. 다들 바쁘고 힘든 일상이지만 주변 풍경도 한 번씩 둘러보시면서 힐링하세요!',
      },
    },
    like_count: 40,
    cheer_count: 31,
    comment_count: 7,
    view_count: 288,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 58).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-14',
    user_id: 'user-pk-14',
    user_name: '라호르청년',
    user_country: 'PK',
    user_flag: '🇵🇰',
    category: 'qna',
    title: '광주 하남공단 근처에 주말(일요일)에도 진료하는 외국인 친화 병원(치과/내과) 있을까요? 🏥',
    content: '평일에는 야근 때문에 병원 가기가 힘든데 어금니 충치 통증이 너무 심해서요. 하남산단이나 송정역 근처에 일요일 오전에도 진료하고 외국인등록증 건강보험 적용 잘 해주는 친절한 치과 아시는 분 추천 부탁드립니다!',
    images: [
      'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=80',
    ],
    region: '광주 광산구',
    industrial_zone: 'gwangju',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '광주 하남공단 근처에 주말(일요일)에도 진료하는 외국인 친화 병원(치과/내과) 있을까요? 🏥',
        content: '평일에는 야근 때문에 병원 가기가 힘든데 어금니 충치 통증이 너무 심해서요. 하남산단이나 송정역 근처에 일요일 오전에도 진료하고 외국인등록증 건강보험 적용 잘 해주는 친절한 치과 아시는 분 추천 부탁드립니다!',
      },
    },
    like_count: 15,
    cheer_count: 7,
    comment_count: 5,
    view_count: 164,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 64).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_COMMUNITY_COMMENTS: Record<string, CommunityComment[]> = {
  'post-1': [
    {
      id: 'comm-1-1',
      post_id: 'post-1',
      user_id: 'user-kr-01',
      user_name: '평택이웃',
      user_country: 'KR',
      user_flag: '🇰🇷',
      content: '반가워요! 저 평택역 근처 사는데 일요일에 시간 괜찮으시면 커피 한잔하면서 한국어 알려드릴게요! 환영합니다 :)',
      source_lang: 'ko',
      translations: {
        ko: '반가워요! 저 평택역 근처 사는데 일요일에 시간 괜찮으시면 커피 한잔하면서 한국어 알려드릴게요! 환영합니다 :)',
      },
      is_hidden: false,
      created_at: new Date(Date.now() - 3600000 * 1.5).toISOString(),
    },
    {
      id: 'comm-1-2',
      post_id: 'post-1',
      user_id: 'user-vn-02',
      user_name: '다낭친구',
      user_country: 'VN',
      user_flag: '🇻🇳',
      content: 'Chào bạn! Mình cũng ở gần chợ Pyeongtaek nè, cuối tuần này cho mình tham gia với nha!',
      source_lang: 'vi',
      translations: {
        ko: '안녕하세요 친구! 저도 평택 시장 근처에 사는데 이번 주말에 저도 같이 껴도 될까요?!',
      },
      is_hidden: false,
      created_at: new Date(Date.now() - 3600000 * 1).toISOString(),
    },
  ],
  'post-2': [
    {
      id: 'comm-2-1',
      post_id: 'post-2',
      user_id: 'user-kr-02',
      user_name: '안산천사',
      user_country: 'KR',
      user_flag: '🇰🇷',
      content: '친구님 힘내세요! 딸아이가 아빠를 정말 자랑스러워할 겁니다. 환절기 감기 조심하시고 따뜻한 밥 챙겨드세요!',
      source_lang: 'ko',
      translations: {
        ko: '친구님 힘내세요! 딸아이가 아빠를 정말 자랑스러워할 겁니다. 환절기 감기 조심하시고 따뜻한 밥 챙겨드세요!',
      },
      is_hidden: false,
      created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    },
  ],
  'post-5': [
    {
      id: 'comm-5-1',
      post_id: 'post-5',
      user_id: 'user-kr-04',
      user_name: '화성노무사',
      user_country: 'KR',
      user_flag: '🇰🇷',
      content: '정리 정말 잘해주셨네요! 추가로 이전 사업장 폐업 등으로 인한 변경일 때는 폐업사실증명원 챙겨가시면 훨씬 수월합니다.',
      source_lang: 'ko',
      translations: {
        ko: '정리 정말 잘해주셨네요! 추가로 이전 사업장 폐업 등으로 인한 변경일 때는 폐업사실증명원 챙겨가시면 훨씬 수월합니다.',
      },
      is_hidden: false,
      created_at: new Date(Date.now() - 3600000 * 16).toISOString(),
    },
  ],
  'post-11': [
    {
      id: 'comm-11-1',
      post_id: 'post-11',
      user_id: 'user-vn-03',
      user_name: '하노이라이더',
      user_country: 'VN',
      user_flag: '🇻🇳',
      content: '우와 축하드려요! 저도 KTRS 배너 보고 신청했는데 어제 140만원 입금 알림톡 받았습니다 ㅎㅎ',
      source_lang: 'ko',
      translations: {
        ko: '우와 축하드려요! 저도 KTRS 배너 보고 신청했는데 어제 140만원 입금 알림톡 받았습니다 ㅎㅎ',
      },
      is_hidden: false,
      created_at: new Date(Date.now() - 3600000 * 42).toISOString(),
    },
  ],
  'post-12': [
    {
      id: 'comm-12-1',
      post_id: 'post-12',
      user_id: 'user-np-03',
      user_name: '카트만두형',
      user_country: 'NP',
      user_flag: '🇳🇵',
      content: '혹시 아직 밥솥 남아있나요? 제가 이번 주에 기숙사 들어왔는데 필요합니다! 오늘 저녁 7시에 갈 수 있어요.',
      source_lang: 'ko',
      translations: {
        ko: '혹시 아직 밥솥 남아있나요? 제가 이번 주에 기숙사 들어왔는데 필요합니다! 오늘 저녁 7시에 갈 수 있어요.',
      },
      is_hidden: false,
      created_at: new Date(Date.now() - 3600000 * 50).toISOString(),
    },
  ],
};
