import { CommunityPost, CommunityComment } from '@/types/community';

export const INITIAL_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'post-1',
    user_id: 'user-vn-01',
    user_name: 'Nguyễn Văn Hùng',
    user_country: 'VN',
    user_flag: '🇻🇳',
    category: 'friends',
    title: '주말에 평택에서 같이 베트남 쌀국수 먹고 한국어 공부할 친구 구해요! 🍜',
    content: '안녕하세요! 한국에 온 지 8개월 된 웅이라고 합니다. 주말마다 혼자 방에만 있으니까 너무 외로워서 글 올려요. 이번 주 일요일 오후에 같이 맛있는 거 먹고 서로 언어 교환(베트남어 ↔ 한국어) 하실 동네 친구분 계신가요? 국적 상관없이 편하게 댓글 남겨주세요!',
    images: [
      'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 평택시',
    industrial_zone: 'pyeongtaek',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '주말에 평택에서 같이 베트남 쌀국수 먹고 한국어 공부할 친구 구해요! 🍜',
        content: '안녕하세요! 한국에 온 지 8개월 된 웅이라고 합니다. 주말마다 혼자 방에만 있으니까 너무 외로워서 글 올려요. 이번 주 일요일 오후에 같이 맛있는 거 먹고 서로 언어 교환(베트남어 ↔ 한국어) 하실 동네 친구분 계신가요? 국적 상관없이 편하게 댓글 남겨주세요!',
      },
      vi: {
        title: 'Tìm bạn cùng ăn phở và học tiếng Hàn cuối tuần này ở Pyeongtaek! 🍜',
        content: 'Xin chào mọi người! Mình sang Hàn được 8 tháng rồi. Cuối tuần ở phòng một mình buồn quá nên đăng bài tìm bạn. Có bạn nào muốn đi ăn cùng và trao đổi ngôn ngữ (Việt - Hàn) vào Chủ Nhật này không? Ai cũng được nha!',
      },
      en: {
        title: 'Looking for a friend to eat pho and study Korean together in Pyeongtaek this weekend! 🍜',
        content: "Hello! I've been in Korea for 8 months. Weekends get lonely staying in my room. Anyone interested in hanging out, having good food, and doing language exchange this Sunday? Everyone is welcome!",
      },
      ne: {
        title: 'यो सप्ताहांत प्योङथेकमा सँगै खाना खाने र कोरियाली भाषा सिक्ने साथी खोज्दैछु! 🍜',
        content: 'नमस्ते! म कोरिया आएको ८ महिना भयो। कोठामा एक्लै बस्दा धेरै एक्लोपन महसुस भयो। यो आइतबार सँगै घुम्न र भाषा सिक्न कोही इच्छुक हुनुहुन्छ?',
      },
    },
    like_count: 14,
    cheer_count: 8,
    comment_count: 4,
    view_count: 128,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-2',
    user_id: 'user-np-02',
    user_name: 'Bikash Shrestha',
    user_country: 'NP',
    user_flag: '🇳🇵',
    category: 'daily_healing',
    title: '오늘 고향에 있는 딸아이와 영상통화 했는데 너무 보고 싶네요.. 힘내봅니다 ☕',
    content: '퇴근하고 네팔에 있는 가족들과 통화했습니다. 5살 딸아이가 아빠 언제 오냐고 묻는데 눈물이 핑 돌더라고요. 가족들 생각하면서 오늘도 야근 열심히 버텼습니다. 한국에서 일하시는 모든 외국인 친구분들, 우리 모두 힘내요!',
    images: [
      'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 안산시',
    industrial_zone: 'ansan',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '오늘 고향에 있는 딸아이와 영상통화 했는데 너무 보고 싶네요.. 힘내봅니다 ☕',
        content: '퇴근하고 네팔에 있는 가족들과 통화했습니다. 5살 딸아이가 아빠 언제 오냐고 묻는데 눈물이 핑 돌더라고요. 가족들 생각하면서 오늘도 야근 열심히 버텼습니다. 한국에서 일하시는 모든 외국인 친구분들, 우리 모두 힘내요!',
      },
      vi: {
        title: 'Hôm nay gọi video cho con gái ở quê mà nhớ quá.. Cùng cố gắng nhé mọi người ☕',
        content: 'Tan ca gọi về cho gia đình ở Nepal. Con gái 5 tuổi hỏi bao giờ bố về mà suýt khóc. Nghĩ đến gia đình nên lại có thêm động lực. Chúc tất cả anh em làm việc tại Hàn Quốc luôn mạnh mẽ!',
      },
      en: {
        title: 'Video called my daughter back home today, miss her so much.. Staying strong ☕',
        content: 'Called my family in Nepal after work. My 5-year-old daughter asked when daddy is coming home and I almost cried. Endured overtime thinking of them. Let’s all stay strong!',
      },
    },
    like_count: 32,
    cheer_count: 27,
    comment_count: 6,
    view_count: 245,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-3',
    user_id: 'user-mn-03',
    user_name: 'Batbayar',
    user_country: 'MN',
    user_flag: '🇲🇳',
    category: 'qna',
    title: '질문: 노란색 종량제 쓰레기봉투는 어디서 사나요? 편의점에서도 파나요?',
    content: '원룸으로 이사 온 지 3일 됐는데 일반 쓰레기는 어떤 봉투에 버려야 하나요? 편의점 가서 종량제 봉투 달라고 하면 주나요?',
    images: [
      'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 화성시',
    industrial_zone: 'hwaseong',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '질문: 노란색 종량제 쓰레기봉투는 어디서 사나요? 편의점에서도 파나요?',
        content: '원룸으로 이사 온 지 3일 됐는데 일반 쓰레기는 어떤 봉투에 버려야 하나요? 편의점 가서 종량제 봉투 달라고 하면 주나요?',
      },
      mn: {
        title: 'Асуулт: Шар өнгийн хогийн уутыг хаанаас авах вэ? CU, GS25-д зардаг уу?',
        content: 'Байрандаа нүүж ирээд 3 хонож байна. Энгийн хогийг ямар уутанд хийж хаях вэ?',
      },
      en: {
        title: 'Q: Where can I buy the standard trash bags? Are they available at convenience stores?',
        content: 'Just moved into a studio 3 days ago. Can I buy municipal garbage bags at GS25 or CU?',
      },
    },
    like_count: 5,
    cheer_count: 2,
    comment_count: 3,
    view_count: 89,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'post-4',
    user_id: 'user-th-04',
    user_name: 'Somchai',
    user_country: 'TH',
    user_flag: '🇹🇭',
    category: 'food_mart',
    title: '화성 향남 근처에 진짜 태국 향신료랑 두리안 파는 아시안 마트 추천합니다 🍲',
    content: '향남읍 행정복지센터 건너편에 새로 생긴 아시안 마트 가봤는데 똠얌 페이스트랑 피쉬소스, 신선한 야채가 다 있네요! 사장님도 엄청 친절하셔서 추천드려요.',
    images: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80',
    ],
    region: '경기 화성시',
    industrial_zone: 'hwaseong',
    source_lang: 'ko',
    translations: {
      ko: {
        title: '화성 향남 근처에 진짜 태국 향신료랑 두리안 파는 아시안 마트 추천합니다 🍲',
        content: '향남읍 행정복지센터 건너편에 새로 생긴 아시안 마트 가봤는데 똠얌 페이스트랑 피쉬소스, 신선한 야채가 다 있네요! 사장님도 엄청 친절하셔서 추천드려요.',
      },
      th: {
        title: 'แนะนำร้านเอเชียใกล้ฮวางซอง ฮยางนัม มีเครื่องต้มยำและทุเรียนขายครับ 🍲',
        content: 'ร้านอยู่ตรงข้ามศูนย์ราชการฮยางนัม มีพริกแกง น้ำปลา ผักสดครบเลยครับ เจ้าของใจดีมาก แนะนำเลยครับ',
      },
      en: {
        title: 'Recommending an Asian grocery store near Hyangnam with authentic spices and ingredients! 🍲',
        content: 'Found a great grocery store across from Hyangnam office. They have fresh tom yum paste, fish sauce, and fresh herbs!',
      },
    },
    like_count: 19,
    cheer_count: 4,
    comment_count: 5,
    view_count: 172,
    is_hidden: false,
    created_at: new Date(Date.now() - 3600000 * 14).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_COMMUNITY_COMMENTS: Record<string, CommunityComment[]> = {
  'post-1': [
    {
      id: 'comm-1-1',
      post_id: 'post-1',
      user_id: 'user-kr-01',
      user_name: '김지현 (Kim Ji-hyun)',
      user_country: 'KR',
      user_flag: '🇰🇷',
      content: '반가워요 웅님! 저 평택역 근처 사는데 일요일에 시간 괜찮으시면 커피 한잔하면서 한국어 알려드릴게요! 환영합니다 :)',
      source_lang: 'ko',
      translations: {
        ko: '반가워요 웅님! 저 평택역 근처 사는데 일요일에 시간 괜찮으시면 커피 한잔하면서 한국어 알려드릴게요! 환영합니다 :)',
        vi: 'Rất vui được làm quen với bạn Hùng! Mình sống gần ga Pyeongtaek, nếu Chủ Nhật rảnh mình mời cà phê và hướng dẫn tiếng Hàn cho bạn nhé! Chào mừng bạn :)',
        en: 'Nice to meet you Hung! I live near Pyeongtaek Station. Happy to have coffee and help you with Korean this Sunday!',
      },
      is_hidden: false,
      created_at: new Date(Date.now() - 3600000 * 1.5).toISOString(),
    },
    {
      id: 'comm-1-2',
      post_id: 'post-1',
      user_id: 'user-vn-02',
      user_name: 'Trần Minh',
      user_country: 'VN',
      user_flag: '🇻🇳',
      content: 'Chào bạn! Mình cũng ở gần chợ Pyeongtaek nè, cuối tuần này cho mình tham gia với nha!',
      source_lang: 'vi',
      translations: {
        ko: '안녕하세요 친구! 저도 평택 시장 근처에 사는데 이번 주말에 저도 같이 껴도 될까요?!',
        vi: 'Chào bạn! Mình cũng ở gần chợ Pyeongtaek nè, cuối tuần này cho mình tham gia với nha!',
        en: 'Hello friend! I live near Pyeongtaek market too, count me in this weekend!',
      },
      is_hidden: false,
      created_at: new Date(Date.now() - 3600000 * 1).toISOString(),
    },
  ],
  'post-2': [
    {
      id: 'comm-2-1',
      post_id: 'post-2',
      user_id: 'user-kr-02',
      user_name: '박민수 (Park Min-soo)',
      user_country: 'KR',
      user_flag: '🇰🇷',
      content: '비카시님 힘내세요! 딸아이가 아빠를 정말 자랑스러워할 겁니다. 환절기 감기 조심하시고 따뜻한 밥 챙겨드세요!',
      source_lang: 'ko',
      translations: {
        ko: '비카시님 힘내세요! 딸아이가 아빠를 정말 자랑스러워할 겁니다. 환절기 감기 조심하시고 따뜻한 밥 챙겨드세요!',
        ne: 'बिकाश जी हिम्मत नहार्नुहोस्! तपाईंको छोरीलाई तपाईंमाथि धेरै गर्व हुनेछ। आफ्नो स्वास्थ्यको ख्याल राख्नुहोला!',
        vi: 'Cố lên anh Bikash nhé! Con gái sẽ rất tự hào về anh. Nhớ giữ gìn sức khỏe và ăn uống đầy đủ nha!',
      },
      is_hidden: false,
      created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    },
    {
      id: 'comm-2-2',
      post_id: 'post-2',
      user_id: 'user-id-01',
      user_name: 'Agus Pratama',
      user_country: 'ID',
      user_flag: '🇮🇩',
      content: 'Semangat kawan! Kita semua berjuang demi keluarga. Semoga sehat selalu!',
      source_lang: 'id',
      translations: {
        ko: '힘내요 친구! 우리 모두 가족을 위해 달리고 있잖아요. 항상 건강하세요!',
        id: 'Semangat kawan! Kita semua berjuang demi keluarga. Semoga sehat selalu!',
        en: 'Keep fighting friend! We are all working hard for our families. Stay healthy!',
      },
      is_hidden: false,
      created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    },
  ],
  'post-3': [
    {
      id: 'comm-3-1',
      post_id: 'post-3',
      user_id: 'user-kr-03',
      user_name: '이수진 (Lee Su-jin)',
      user_country: 'KR',
      user_flag: '🇰🇷',
      content: '네! 가까운 편의점(CU, GS25, 세븐일레븐) 카운터에서 "화성시 종량제 봉투 10리터나 20리터 주세요" 하시면 현금이나 카드로 바로 살 수 있어요!',
      source_lang: 'ko',
      translations: {
        ko: '네! 가까운 편의점(CU, GS25, 세븐일레븐) 카운터에서 "화성시 종량제 봉투 10리터나 20리터 주세요" 하시면 현금이나 카드로 바로 살 수 있어요!',
        mn: 'Тийм ээ! Ойролцоох CU эсвэл GS25 дэлгүүрийн касс дээр очоод "Хогийн уут 10L эсвэл 20L авъя" гэж хэлээд худалдаж авч болно!',
        en: 'Yes! Just ask the cashier at any convenience store for a 10L or 20L municipal trash bag.',
      },
      is_hidden: false,
      created_at: new Date(Date.now() - 3600000 * 7).toISOString(),
    },
  ],
};
