import { LanguageOption, SupportedLanguage } from '@/types/kmarket';

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'ko', name: '한국어', nativeName: '한국어', flag: '🇰🇷', countryCode: 'KR' },
  { code: 'vi', name: '베트남어', nativeName: 'Tiếng Việt', flag: '🇻🇳', countryCode: 'VN' },
  { code: 'en', name: '영어', nativeName: 'English', flag: '🇺🇸', countryCode: 'US' },
  { code: 'ne', name: '네팔어', nativeName: 'नेपाली', flag: '🇳🇵', countryCode: 'NP' },
  { code: 'th', name: '태국어', nativeName: 'ไทย', flag: '🇹🇭', countryCode: 'TH' },
  { code: 'my', name: '미얀마어', nativeName: 'မြန်မာ', flag: '🇲🇲', countryCode: 'MM' },
  { code: 'km', name: '캄보디아어', nativeName: 'ភាសាខ្មែរ', flag: '🇰🇭', countryCode: 'KH' },
  { code: 'mn', name: '몽골어', nativeName: 'Монгол', flag: '🇲🇳', countryCode: 'MN' },
  { code: 'uz', name: '우즈베크어', nativeName: "O'zbek", flag: '🇺🇿', countryCode: 'UZ' },
  { code: 'tl', name: '필리핀어', nativeName: 'Tagalog', flag: '🇵🇭', countryCode: 'PH' },
  { code: 'id', name: '인도네시아어', nativeName: 'Bahasa Indonesia', flag: '🇮🇩', countryCode: 'ID' },
  { code: 'si', name: '스리랑카어', nativeName: 'සිංහල', flag: '🇱🇰', countryCode: 'LK' },
  { code: 'bn', name: '방글라데시어', nativeName: 'বাংলা', flag: '🇧🇩', countryCode: 'BD' },
  { code: 'zh', name: '중국어', nativeName: '中文', flag: '🇨🇳', countryCode: 'CN' },
  { code: 'ru', name: '러시아어', nativeName: 'Русский', flag: '🇷🇺', countryCode: 'RU' },
];

export const REGIONS_DATA = [
  { id: 'all', nameKo: '전체 공단', nameEn: 'All Zones', icon: '🏭' },
  { id: 'pyeongtaek', nameKo: '평택 포승/고덕', nameEn: 'Pyeongtaek Poseung', icon: '📍' },
  { id: 'ansan', nameKo: '안산 반월/원곡동', nameEn: 'Ansan Wongok', icon: '📍' },
  { id: 'hwaseong', nameKo: '화성 향남/남양', nameEn: 'Hwaseong Hyangnam', icon: '📍' },
  { id: 'siheung', nameKo: '시흥 정왕/스마트', nameEn: 'Siheung Jeongwang', icon: '📍' },
  { id: 'gumi', nameKo: '구미 국가산단', nameEn: 'Gumi Industrial', icon: '📍' },
  { id: 'gimhae', nameKo: '김해 골든루트', nameEn: 'Gimhae Golden', icon: '📍' },
  { id: 'incheon', nameKo: '인천 남동공단', nameEn: 'Incheon Namdong', icon: '📍' },
  { id: 'gwangju', nameKo: '광주 하남공단', nameEn: 'Gwangju Hanam', icon: '📍' },
];

export const CATEGORIES_DATA = [
  { id: 'all', nameKo: '전체 매물', icon: '🛍️' },
  { id: 'moving_sale', nameKo: '무빙세일(귀국급처)', icon: '✈️' },
  { id: 'appliances', nameKo: '가전제품', icon: '🔌' },
  { id: 'furniture', nameKo: '가구/매트리스', icon: '🛏️' },
  { id: 'digital', nameKo: '전자기기/폰', icon: '📱' },
  { id: 'vehicles', nameKo: '자전거/킥보드', icon: '🚲' },
  { id: 'clothes', nameKo: '의류/생활용품', icon: '👕' },
  { id: 'free_give', nameKo: '무료 나눔(0원)', icon: '🎁' },
];

export const UI_TRANSLATIONS: Record<string, Record<SupportedLanguage, string>> = {
  app_name: {
    ko: 'K-Market',
    vi: 'K-Market',
    en: 'K-Market',
    ne: 'K-Market',
    th: 'K-Market',
    my: 'K-Market',
    km: 'K-Market',
    mn: 'K-Market',
    uz: 'K-Market',
    tl: 'K-Market',
    id: 'K-Market',
    si: 'K-Market',
    bn: 'K-Market',
    zh: 'K-Market',
    ru: 'K-Market',
  },
  app_slogan: {
    ko: '외국인 근로자 0원 무료 중고거래 & 무빙세일',
    vi: 'Chợ đồ cũ & Thanh lý về nước 0 đồng cho lao động',
    en: 'Zero-Fee Used Market & Moving Sale for Foreigners',
    ne: 'विदेशी कामदारहरूको लागि नि:शुल्क सेकेन्ड-ह्यान्ड बजार',
    th: 'ตลาดมือสองและขายเหมากลับประเทศ ฟรีค่าธรรมเนียม',
    my: 'နိုင်ငံခြားသားများအတွက် အခမဲ့ တစ်ပတ်ရစ်စျေးကွက်',
    km: 'ផ្សារទំនិញជជុះ និងលក់បង្ហើយត្រឡប់ទៅស្រុកឥតគិតថ្លៃ',
    mn: 'Гадаад иргэдэд зориулсан үнэ төлбөргүй хуучин барааны зах',
    uz: "Xorijiy ishchilar uchun 0 so'mlik bepul bozor",
    tl: 'Libreng Used Items & Moving Sale para sa Dayuhan',
    id: 'Pasar Barang Bekas & Cuci Gudang Pulang Kampung Gratis',
    si: 'විදේශිකයන් සඳහා නොමිලේ පාවිච්චි කළ බඩු වෙළඳපොළ',
    bn: 'বিদেশি কর্মীদের জন্য সম্পূর্ণ ফ্রি সেকেন্ড-হ্যান্ড মার্কেট',
    zh: '外籍务工者0手续费二手交易与归国清仓',
    ru: 'Бесплатная барахолка и распродажа для иностранцев',
  },
  ktrs_tab_tax: {
    ko: '💰 세무 환급 (184만)',
    vi: '💰 Hoàn thuế (1,84tr)',
    en: '💰 Tax Refund ($1,400)',
    ne: '💰 कर फिर्ता (१८.४ लाख)',
    th: '💰 ขอคืนภาษี (1.84 ล้าน)',
    my: '💰 အခွန်ပြန်အမ်းငွေ (၁.၈၄ သန်း)',
    km: '💰 សងពន្ធវិញ (១.៨៤លាន)',
    mn: '💰 Татварын буцаан олголт',
    uz: '💰 Soliq qaytarish (1.84mln)',
    tl: '💰 Tax Refund (1.84M)',
    id: '💰 Pengembalian Pajak (1,84jt)',
    si: '💰 බදු ආපසු ගෙවීම',
    bn: '💰 ট্যাক্স রিফান্ড (১৮.৪ লাখ)',
    zh: '💰 退税申请 (184万)',
    ru: '💰 Возврат налога (1.84 млн)',
  },
  ktrs_tab_loan: {
    ko: '⚡ 비상금 대출',
    vi: '⚡ Vay khẩn cấp',
    en: '⚡ Emergency Loan',
    ne: '⚡ आकस्मिक ऋण',
    th: '⚡ เงินกู้ฉุกเฉิน',
    my: '⚡ အရေးပေါ် ချေးငွေ',
    km: '⚡ កម្ចីបន្ទាន់',
    mn: '⚡ Яаралтай зээл',
    uz: '⚡ Shoshilinch qarz',
    tl: '⚡ Emergency Loan',
    id: '⚡ Pinjaman Darurat',
    si: '⚡ හදිසි ණය',
    bn: '⚡ জরুরি লোন',
    zh: '⚡ 应急借款',
    ru: '⚡ Срочный займ',
  },
  ktrs_tab_housing: {
    ko: '🏠 안심 원룸',
    vi: '🏠 Phòng trọ an tâm',
    en: '🏠 Safe Housing',
    ne: '🏠 सुरक्षित कोठा',
    th: '🏠 ห้องพักปลอดภัย',
    my: '🏠 လုံခြုံသော အိမ်ခန်း',
    km: '🏠 បន្ទប់ជួលសុវត្ថិភាព',
    mn: '🏠 Аюулгүй байр',
    uz: '🏠 Ishonchli xona',
    tl: '🏠 Ligtas na Kwarto',
    id: '🏠 Sewa Kamar Aman',
    si: '🏠 ආරක්ෂිත නවාතැන්',
    bn: '🏠 নিরাপদ রুম',
    zh: '🏠 放心租房',
    ru: '🏠 Безопасное жилье',
  },
  ktrs_tab_market: {
    ko: '🛒 K-Market (중고/무빙)',
    vi: '🛒 K-Market (Đồ cũ/Moving)',
    en: '🛒 K-Market (Used/Moving)',
    ne: '🛒 K-Market (बजार/सामान)',
    th: '🛒 K-Market (มือสอง/เหมา)',
    my: '🛒 K-Market (တစ်ပတ်ရစ်)',
    km: '🛒 K-Market (ជជុះ/លក់បង្ហើយ)',
    mn: '🛒 K-Market (Зах/Нүүдэл)',
    uz: '🛒 K-Market (Bozor)',
    tl: '🛒 K-Market (Used/Moving)',
    id: '🛒 K-Market (Barang Bekas)',
    si: '🛒 K-Market (වෙළඳපොළ)',
    bn: '🛒 কে-মার্কেট (সেকেন্ড-হ্যান্ড)',
    zh: '🛒 K-Market (二手/清仓)',
    ru: '🛒 K-Market (Барахолка)',
  },
  tax_banner_title: {
    ko: '한국 근무 1년 이상? 떼인 세금 [평균 184만원] 30초 무료 환급 조회!',
    vi: 'Làm việc tại Hàn trên 1 năm? Kiểm tra hoàn thuế [1,84 triệu won] miễn phí trong 30 giây!',
    en: 'Worked in Korea 1+ yr? Check [Avg ₩1.84M] Tax Refund in 30s for FREE!',
    ne: 'कोरियामा १ वर्ष+ काम गर्नुभयो? ३० सेकेन्डमा [औसत १८.४ लाख वन] कर फिर्ता निःशुल्क हेर्नुहोस्!',
    th: 'ทำงานในเกาหลี 1 ปีขึ้นไป? ตรวจสอบเงินคืนภาษี [เฉลี่ย 1.84 ล้านวอน] ฟรีใน 30 วินาที!',
    my: 'ကိုရီးယားတွင် ၁ နှစ်အထက် အလုပ်လုပ်ခဲ့သလား? အခွန်ပြန်အမ်းငွေ [၁.၈၄ သန်း] ၃၀ စက္ကန့်အတွင်း အခမဲ့ စစ်ဆေးပါ!',
    km: 'ធ្វើការនៅកូរ៉េលើសពី ១ ឆ្នាំ? ពិនិត្យប្រាក់ពន្ធសងវិញ [ជាមធ្យម ១.៨៤លានវ៉ុន] ឥតគិតថ្លៃក្នុង ៣០ វិនាទី!',
    mn: 'Солонгост 1+ жил ажилласан уу? Татварын буцаан олголт [1.84 сая вон] 30 секундэд үнэгүй шалгах!',
    uz: "Koreyada 1 yildan ortiq ishladingizmi? [1.84 mln von] soliq qaytarishni 30 soniyada bepul tekshiring!",
    tl: 'Nagtatrabaho sa Korea ng 1+ taon? Suriin ang [Avg ₩1.84M] Tax Refund sa 30 segundo nang LIBRE!',
    id: 'Bekerja di Korea 1+ tahun? Cek pengembalian pajak [rata-rata 1,84 juta won] gratis dlm 30 detik!',
    si: 'කොරියාවේ වසර 1+ සේවය කළාද? තත්පර 30 කින් නොමිලේ බදු ආපසු මුදල [1.84M] පරීක්ෂා කරන්න!',
    bn: 'কোরিয়ায় ১+ বছর কাজ করেছেন? ৩০ সেকেন্ডে [গড়ে ১৮.৪ লাখ ওন] ট্যাক্স রিফান্ড ফ্রি চেক করুন!',
    zh: '在韩国工作1年以上？30秒免费查询未退税款 [平均184万韩元]！',
    ru: 'Работаете в Корее больше года? Проверьте возврат налога [1.84 млн вон] бесплатно за 30 сек!',
  },
  tax_banner_btn: {
    ko: '내 환급금 지금 조회하기 ➔',
    vi: 'Kiểm tra tiền hoàn ngay ➔',
    en: 'Check My Refund Now ➔',
    ne: 'मेरो कर फिर्ता रकम हेर्नुहोस् ➔',
    th: 'เช็คเงินคืนของฉันตอนนี้ ➔',
    my: 'ငွေပြန်အမ်းစစ်ဆေးမည် ➔',
    km: 'ពិនិត្យប្រាក់សងវិញឥឡូវនេះ ➔',
    mn: 'Одоо шалгах ➔',
    uz: 'Pulimni tekshirish ➔',
    tl: 'Tingnan ang Refund Ko ➔',
    id: 'Cek Pengembalian Sekarang ➔',
    si: 'මුදල පරීක්ෂා කරන්න ➔',
    bn: 'আমার রিফান্ড চেক করুন ➔',
    zh: '立即查询我的退税 ➔',
    ru: 'Узнать сумму возврата ➔',
  },
  moving_sale_title: {
    ko: '✈️ 귀국 D-7 초특가 [무빙 세일(Moving Sale)]',
    vi: '✈️ Thanh lý gấp về nước D-7 [Moving Sale Siêu Rẻ]',
    en: '✈️ Returning Home D-7 [Moving Sale Mega Deals]',
    ne: '✈️ घर फिर्ता D-7 [मुभिङ सेल भारी छुट]',
    th: '✈️ กลับประเทศ D-7 [Moving Sale ลดล้างสต๊อก]',
    my: '✈️ ပြည်တော်ပြန် D-7 [အထူးလျှော့စျေးရောင်းပွဲ]',
    km: '✈️ ត្រឡប់ទៅស្រុកវិញ D-7 [ការលក់បង្ហើយ Moving Sale]',
    mn: '✈️ Буцах дөхсөн D-7 [Хямд нүүдлийн худалдаа]',
    uz: "✈️ Vatinga qaytish D-7 [Arzon Moving Sale]",
    tl: '✈️ Uuwi na D-7 [Moving Sale Rush Deals]',
    id: '✈️ Mau Pulang D-7 [Cuci Gudang Super Murah]',
    si: '✈️ ආපසු රටට D-7 [විශේෂ වට්ටම් සහිත විකිණීම]',
    bn: '✈️ দেশে ফেরা D-7 [মুভিং সেল বাম্পার ছাড়]',
    zh: '✈️ 归国D-7甩卖 [清仓 Moving Sale]',
    ru: '✈️ Скорый отъезд D-7 [Распродажа Moving Sale]',
  },
  moving_sale_badge: {
    ko: '급처분 묶음할인',
    vi: 'Gói đại hạ giá',
    en: 'Bundle Clearance',
    ne: 'भारी छुट बन्डल',
    th: 'มัดรวมราคาถูก',
    my: 'အထူးအတွဲလျှော့စျေး',
    km: 'បញ្ចុះតម្លៃជាកញ្ចប់',
    mn: 'Багцын хямдрал',
    uz: 'Paket arzon narx',
    tl: 'Bundle Clearance',
    id: 'Diskon Borongan',
    si: 'පැකේජ වට්ටම්',
    bn: 'বান্ডিল ডিসকাউন্ট',
    zh: '打包超值清仓',
    ru: 'Скидка на комплект',
  },
  post_item_btn: {
    ko: '✏️ 1분 간편 매물 등록',
    vi: '✏️ Đăng bán trong 1 phút',
    en: '✏️ Post Item in 1 Min',
    ne: '✏️ १ मिनेटमा सामान बेच्नुहोस्',
    th: '✏️ ลงขายง่ายใน 1 นาที',
    my: '✏️ ၁ မိနစ်အတွင်း ပစ္စည်းတင်ပါ',
    km: '✏️ ចុះលក់ក្នុង ១ នាទី',
    mn: '✏️ 1 минутад бараа зарах',
    uz: "✏️ 1 daqiqada e'lon berish",
    tl: '✏️ Magbenta sa 1 Minuto',
    id: '✏️ Pasang Iklan 1 Menit',
    si: '✏️ විනාඩි 1 කින් විකුණන්න',
    bn: '✏️ ১ মিনিটে পণ্য পোস্ট করুন',
    zh: '✏️ 1分钟极速发布',
    ru: '✏️ Продать за 1 мин',
  },
  chat_btn: {
    ko: '💬 1:1 실시간 자동번역 채팅',
    vi: '💬 Chat dịch tự động 1:1',
    en: '💬 1:1 Real-time Auto Translate Chat',
    ne: '💬 १:१ प्रत्यक्ष अनुवाद च्याट',
    th: '💬 แชทแปลสดอัตโนมัติ 1:1',
    my: '💬 ၁:၁ တိုက်ရိုက်ဘာသာပြန်ချက်',
    km: '💬 ជជែកបកប្រែផ្ទាល់ ១:១',
    mn: '💬 Шууд орчуулгатай чат',
    uz: '💬 1:1 Jonli tarjima chat',
    tl: '💬 1:1 Real-time Translate Chat',
    id: '💬 Chat Terjemahan Otomatis 1:1',
    si: '💬 සජීවී පරිවර්තන චැට්',
    bn: '💬 ১:১ রিয়েল-টাইম অনুবাদ চ্যাট',
    zh: '💬 1:1实时自动翻译聊天',
    ru: '💬 1:1 Чат с автопереводом',
  },
  chat_translation_hint: {
    ko: '✨ 상대방 모국어로 0.3초 만에 실시간 번역되어 전송됩니다 (Gemini AI 탑재)',
    vi: '✨ Tự động dịch sang ngôn ngữ đối phương sau 0.3 giây bằng Gemini AI',
    en: '✨ Translated to partner language in 0.3s powered by Gemini AI',
    ne: '✨ Gemini AI द्वारा ०.३ सेकेन्डमा स्वतः अनुवाद हुन्छ',
    th: '✨ แปลเป็นภาษาคู่สนทนาอัตโนมัติใน 0.3 วินาทีด้วย Gemini AI',
    my: '✨ Gemini AI ဖြင့် ၀.၃ စက္ကန့်အတွင်း အလိုအလျောက် ဘာသာပြန်ပေးသည်',
    km: '✨ បកប្រែដោយស្វ័យប្រវត្តទៅភាសាដៃគូក្នុង ០.៣ វិនាទីដោយ Gemini AI',
    mn: '✨ Gemini AI ашиглан 0.3 секундэд шууд орчуулагдана',
    uz: "✨ Gemini AI orqali 0.3 soniyada suhbatdosh tiliga tarjima qilinadi",
    tl: '✨ Awtomatikong isinasalin sa 0.3s gamit ang Gemini AI',
    id: '✨ Diterjemahkan otomatis dlm 0.3 detik didukung Gemini AI',
    si: '✨ Gemini AI මඟින් තත්පර 0.3 කින් ස්වයංක්‍රීයව පරිවර්තනය වේ',
    bn: '✨ জেমিনি এআই দিয়ে ০.৩ সেকেন্ডে স্বয়ংক্রিয় অনুবাদ হয়',
    zh: '✨ 基于 Gemini AI，0.3秒内自动双向翻译',
    ru: '✨ Мгновенный перевод на язык собеседника за 0.3 сек через Gemini AI',
  },
  free_share: {
    ko: '무료나눔',
    vi: 'Tặng miễn phí',
    en: 'Free Giveaway',
    ne: 'निःशुल्क',
    th: 'แจกฟรี',
    my: 'အခမဲ့ပေးခြင်း',
    km: 'ចែកឥតគិតថ្លៃ',
    mn: 'Үнэгүй өгнө',
    uz: 'Tekin berish',
    tl: 'Libre / Pamigay',
    id: 'Gratis',
    si: 'නොමිලේ',
    bn: 'বিনামূল্যে',
    zh: '免费赠送',
    ru: 'Бесплатно / Отдам даром',
  },
  filter_all_regions: {
    ko: '전국 공단 직거래',
    vi: 'Khu công nghiệp toàn quốc',
    en: 'Nationwide Industrial Zones',
    ne: 'सबै औद्योगिक क्षेत्रहरू',
    th: 'ทุกนิคมอุตสาหกรรม',
    my: 'စက်မှုဇုန်အားလုံး',
    km: 'តំបន់ឧស្សាហកម្មទាំងអស់',
    mn: 'Бүх үйлдвэрийн бүс',
    uz: 'Barcha sanoat zonalari',
    tl: 'Lahat ng Industrial Zones',
    id: 'Semua Kawasan Industri',
    si: 'සියලුම කාර්මික කලාප',
    bn: 'সকল শিল্পাঞ্চল',
    zh: '全国各大工业园区',
    ru: 'Все промзоны Кореи',
  },
  search_placeholder: {
    ko: '공단 근처 매물 검색 (세탁기, 자전거, 밥솥 등)...',
    vi: 'Tìm đồ gần khu công nghiệp (máy giặt, xe đạp, nồi cơm)...',
    en: 'Search items near industrial zones (washer, bike, rice cooker)...',
    ne: 'औद्योगिक क्षेत्र नजिक सामान खोज्नुहोस्...',
    th: 'ค้นหาสินค้าใกล้นิคม (เครื่องซักผ้า, จักรยาน, หม้อหุงข้าว)...',
    my: 'စက်မှုဇုန်အနီး ပစ္စည်းရှာဖွေရန်...',
    km: 'ស្វែងរកទំនិញក្បែរតំបន់ឧស្សាហកម្ម...',
    mn: 'Үйлдвэрийн бүсийн бараа хайх...',
    uz: 'Sanoat zonasi atrofidan qidirish...',
    tl: 'Maghanap ng gamit malapit sa pabrika...',
    id: 'Cari barang dekat pabrik (mesin cuci, sepeda, rice cooker)...',
    si: 'කාර්මික කලාපය අසල බඩු සොයන්න...',
    bn: 'শিল্পাঞ্চলের কাছাকাছি পণ্য খুঁজুন...',
    zh: '搜索园区附近二手好物（洗衣机、电饭煲、自行车等）...',
    ru: 'Поиск вещей рядом с промзоной (стиралка, велик, рисоварка)...',
  },
  status_selling: {
    ko: '판매중',
    vi: 'Đang bán',
    en: 'Selling',
    ne: 'बिक्रीमा',
    th: 'กำลังขาย',
    my: 'ရောင်းရန်ရှိ',
    km: 'កំពុងលក់',
    mn: 'Зарж байна',
    uz: 'Sotilmoqda',
    tl: 'Available',
    id: 'Dijual',
    si: 'විකිණීමට ඇත',
    bn: 'বিক্রি চলছে',
    zh: '出售中',
    ru: 'Продается',
  },
  status_reserved: {
    ko: '예약중',
    vi: 'Đã cọc/hẹn',
    en: 'Reserved',
    ne: 'आरक्षित',
    th: 'ติดจอง',
    my: 'ကြိုတင်ထားသည်',
    km: 'កក់រួច',
    mn: 'Захиалсан',
    uz: 'Band qilingan',
    tl: 'Reserved',
    id: 'Dibooking',
    si: 'වෙන්කර ඇත',
    bn: 'বুক করা হয়েছে',
    zh: '已预约',
    ru: 'Забронировано',
  },
  status_sold: {
    ko: '거래완료',
    vi: 'Đã bán',
    en: 'Sold',
    ne: 'बिक्री भयो',
    th: 'ขายแล้ว',
    my: 'ရောင်းပြီး',
    km: 'លក់ដាច់ហើយ',
    mn: 'Зарагдсан',
    uz: 'Sotildi',
    tl: 'Sold Out',
    id: 'Terjual',
    si: 'විකුණා අවසන්',
    bn: 'বিক্রি সম্পন্ন',
    zh: '已售出',
    ru: 'Продано',
  },
  walk_trade_available: {
    ko: '도보 5분 직거래 가능',
    vi: 'Giao dịch trực tiếp đi bộ 5 phút',
    en: '5-min walk direct meetup',
    ne: '५ मिनेट हिँडेर भेट्न सकिने',
    th: 'นัดรับเดิน 5 นาที',
    my: '၅ မိနစ်လမ်းလျှောက် လူချင်းတွေ့ယူနိုင်',
    km: 'ដើរ ៥ នាទីជួបផ្ទាល់',
    mn: '5 мин алхаад уулзаж авна',
    uz: '5 daqiqa piyoda uchrashuv',
    tl: '5-min lakad kaliwaan',
    id: 'COD jalan kaki 5 menit',
    si: 'විනාඩි 5 කින් හමුවිය හැක',
    bn: '৫ মিনিট হেঁটে দেখা করে নেওয়া যাবে',
    zh: '步行5分钟当面自提',
    ru: 'Самовывоз 5 мин пешком',
  },
  zero_fee_badge: {
    ko: '수수료 0원 100% 무료',
    vi: 'Phí 0 đồng 100% miễn phí',
    en: '0 Fee 100% Free',
    ne: 'शुल्क ० वन १००% निःशुल्क',
    th: 'ค่าธรรมเนียม 0 วอน ฟรี 100%',
    my: 'အခကြေးငွေ လုံးဝမယူပါ',
    km: 'កម្រៃជើងសារ ០ រៀល',
    mn: '0 хураамж 100% үнэгүй',
    uz: "Komissiya 0 so'm",
    tl: 'Zero Fee 100% Libre',
    id: 'Biaya Admin 0 Rupiah',
    si: 'ගාස්තු රහිතයි 100% නොමිලේ',
    bn: 'কমিশন ০ ওন ১০০% ফ্রি',
    zh: '0手续费 100%免费',
    ru: 'Комиссия 0 вон (100% бесплатно)',
  }
};
