import { KMarketChat, KMarketItem } from '@/types/kmarket';

export const INITIAL_ITEMS: KMarketItem[] = [
  {
    id: 'item-1',
    seller_id: 'user-vn-1',
    seller_name: '호치민호랑이',
    seller_phone: '010-3849-1123',
    seller_country: 'VN',
    seller_country_flag: '🇻🇳',
    title: '✈️ [귀국 D-5 무빙세일] 세탁기 10kg + 쿠쿠 밥솥 + 전자레인지 묶음 급처',
    description: '이번 주 일요일 비자 만료로 베트남 완전 귀국합니다! 원룸에서 1년 동안 깨끗하게 쓰던 통돌이 세탁기 10kg, 쿠쿠 밥솥, 삼성 전자레인지 전부 묶어서 8만원에 드립니다. 작동 완벽하고 오늘 저녁 바로 가져가실 수 있습니다. 포승공단 기숙사 근처 도보 5분 직거래 가능합니다.',
    price: 80000,
    original_price: 550000,
    category: 'moving_sale',
    images: [
      'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=800&auto=format&fit=crop&q=80'
    ],
    region: '평택 포승공단 기숙사 입구',
    industrial_zone: 'pyeongtaek',
    status: 'selling',
    view_count: 142,
    like_count: 28,
    is_moving_sale: true,
    moving_d_day: 5,
    source_lang: 'vi',
    translations: {
      vi: {
        title: '✈️ [Về nước D-5 Moving Sale] Combo Máy giặt 10kg + Nồi cơm Cuckoo + Lò vi sóng thanh lý gấp',
        description: 'Chủ nhật này hết hạn visa về Việt Nam luôn! Nhượng lại combo máy giặt 10kg, nồi cơm Cuckoo, lò vi sóng Samsung dùng 1 năm còn rất mới giá 80k won. Giao dịch đi bộ 5 phút gần KTX Poseung Pyeongtaek.',
      },
      en: {
        title: '✈️ [Moving Sale D-5] Washing Machine 10kg + Cuckoo Rice Cooker + Microwave Bundle',
        description: 'Returning to Vietnam this Sunday due to visa expiration! Selling full bundle of 10kg washing machine, Cuckoo rice cooker, and microwave used for 1 yr. All works perfect. 5-min walk meetup near Pyeongtaek Poseung dorm.',
      },
      ne: {
        title: '✈️ [घर फिर्ता D-5 मुभिङ सेल] वाशिङ मेसिन १० केजी + कुकु राइस कुकर + माइक्रोवेभ बन्डल',
        description: 'यो आइतबार भिसा सकिएर भियतनाम फर्किँदैछु! १ वर्ष प्रयोग गरेको वाशिङ मेसिन, राइस कुकर र माइक्रोवेभ जम्मा ८० हजार वोनमा दिँदैछु। प्योङतेक पोसुङ नजिक ५ मिनेटमा भेटेर लिन सकिन्छ।',
      },
    },
    created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: 'item-2',
    seller_id: 'user-np-1',
    seller_name: '포카라친구',
    seller_phone: '010-8273-9941',
    seller_country: 'NP',
    seller_country_flag: '🇳🇵',
    title: '✈️ [귀국 D-3 급처분] 소형 2도어 냉장고 + 스탠드 선풍기 2대 + 3단 수납장',
    description: '네팔 귀국 3일 남아서 원룸 가구/가전 헐값에 넘깁니다. 냉장고 냉동/냉장 아주 시원하게 잘 되고, 선풍기 2대와 깨끗한 수납장까지 다 드립니다. 원곡동 다문화거리 근처입니다.',
    price: 60000,
    original_price: 420000,
    category: 'moving_sale',
    images: [
      'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80'
    ],
    region: '안산 원곡동 다문화거리',
    industrial_zone: 'ansan',
    status: 'selling',
    view_count: 98,
    like_count: 19,
    is_moving_sale: true,
    moving_d_day: 3,
    source_lang: 'ne',
    translations: {
      ne: {
        title: '✈️ [घर फिर्ता D-3 सेल] सानो २-ढोके फ्रिज + २ वटा स्ट्यान्ड फ्यान + ३-तले दराज',
        description: 'नेपाल फर्कन ३ दिन मात्र बाँकी रहेकाले कोठाका सामान सस्तोमा बेच्दैछु। फ्रिज राम्रोसँग चल्छ, २ वटा फ्यान र दराज सबै ६० हजार वनमा। अनसान वनगोक-दोङ नजिक।',
      },
      vi: {
        title: '✈️ [Về nước D-3] Tủ lạnh 2 cánh mini + 2 quạt cây + Tủ kệ 3 tầng thanh lý rẻ',
        description: 'Còn 3 ngày nữa về Nepal nên thanh lý hết đồ trọ giá rẻ. Tủ lạnh làm lạnh tốt, kèm 2 quạt và kệ tủ sạch sẽ. Gần phố đa văn hóa Wongok Ansan.',
      },
      en: {
        title: '✈️ [Moving Sale D-3] 2-Door Mini Refrigerator + 2 Stand Fans + 3-Tier Storage',
        description: 'Leaving for Nepal in 3 days. Super cheap clearance for fridge, 2 fans and storage shelf. ₩60,000 all included. Wongok-dong Ansan.',
      },
    },
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'item-3',
    seller_id: 'user-th-1',
    seller_name: '방콕라이더',
    seller_phone: '010-5591-3310',
    seller_country: 'TH',
    seller_country_flag: '🇹🇭',
    title: '✈️ [귀국 급처] 샤오미 전동 킥보드 Pro2 + 스마트 헬멧 + 충전기',
    description: '태국으로 복귀하게 되어 출퇴근 때 타던 샤오미 전동 킥보드 팝니다. 완충 시 40km 주행 가능하고 브레이크 패드 교체 완료했습니다. 시흥 정왕역 2번 출구 직거래 희망합니다.',
    price: 90000,
    original_price: 450000,
    category: 'vehicles',
    images: [
      'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=800&auto=format&fit=crop&q=80'
    ],
    region: '시흥 정왕역 / 스마트허브',
    industrial_zone: 'siheung',
    status: 'selling',
    view_count: 210,
    like_count: 45,
    is_moving_sale: true,
    moving_d_day: 7,
    source_lang: 'th',
    created_at: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
  },
  {
    id: 'item-4',
    seller_id: 'user-uz-1',
    seller_name: '타슈켄트따뜻',
    seller_phone: '010-9912-4456',
    seller_country: 'UZ',
    seller_country_flag: '🇺🇿',
    title: '🎁 [무료 나눔 0원] 겨울 롱패딩(L) 2벌 + 1인용 온수매트 필요하신 분 드려요',
    description: '우즈베키스탄 동료들과 나누려다 남아서 다른 외국인 근로자 분께 0원 무료 나눔합니다. 따뜻하고 찢어진 곳 없습니다. 안산 반월공단 정문에서 저녁 7시 이후 전달 가능합니다.',
    price: 0,
    original_price: 150000,
    category: 'free_give',
    images: [
      'https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800&auto=format&fit=crop&q=80'
    ],
    region: '안산 반월공단 정문',
    industrial_zone: 'ansan',
    status: 'selling',
    view_count: 310,
    like_count: 72,
    is_moving_sale: false,
    source_lang: 'uz',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'item-5',
    seller_id: 'user-vn-2',
    seller_name: '다낭마켓러',
    seller_phone: '010-7711-2099',
    seller_country: 'VN',
    seller_country_flag: '🇻🇳',
    title: '📱 아이폰 13 128GB 미드나이트 (배터리 88%, 유심 프리)',
    description: '한국 알뜰폰/해외 유심 모두 잘 되는 아이폰13 128GB 판매합니다. 액정 강화유리 붙어있고 케이스 2개 같이 드립니다. 평택 고덕 삼성반도체 앞 직거래 가능합니다.',
    price: 270000,
    original_price: 850000,
    category: 'digital',
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80'
    ],
    region: '평택 고덕 삼성캠퍼스 앞',
    industrial_zone: 'pyeongtaek',
    status: 'selling',
    view_count: 185,
    like_count: 33,
    is_moving_sale: false,
    source_lang: 'vi',
    created_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
  },
  {
    id: 'item-6',
    seller_id: 'user-kh-1',
    seller_name: '프놈펜스마일',
    seller_phone: '010-4491-6672',
    seller_country: 'KH',
    seller_country_flag: '🇰🇭',
    title: '✈️ [귀국 D-14 무빙세일] 접이식 싱글 침대 매트리스 + 책상 + 행거 세트 (2주 전 예약)',
    description: '화성 향남 제약공단 기숙사 2주 뒤 퇴실 예정이라 가구 세트 35,000원에 미리 예약 처분합니다. 매트리스 쿠션감 좋고 오염 없습니다. 미리 날짜 맞춰 거래 가능합니다.',
    price: 35000,
    original_price: 260000,
    category: 'moving_sale',
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80'
    ],
    region: '화성 향남 제약공단',
    industrial_zone: 'hwaseong',
    status: 'selling',
    view_count: 88,
    like_count: 14,
    is_moving_sale: true,
    moving_d_day: 14,
    source_lang: 'km',
    created_at: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
  },
  {
    id: 'item-7',
    seller_id: 'user-lk-1',
    seller_name: '콜롬보이웃',
    seller_phone: '010-6622-9011',
    seller_country: 'LK',
    seller_country_flag: '🇱🇰',
    title: '🔌 쿠쿠 6인용 압력 밥솥 + 보온 기능 완벽',
    description: '밥 정말 찰지게 잘 되는 쿠쿠 압력밥솥입니다. 내솥 코팅 깨끗합니다. 김해 골든루트 산업단지 인근 도보 직거래 가능합니다.',
    price: 25000,
    original_price: 130000,
    category: 'appliances',
    images: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&auto=format&fit=crop&q=80'
    ],
    region: '김해 골든루트 산단',
    industrial_zone: 'gimhae',
    status: 'selling',
    view_count: 67,
    like_count: 11,
    is_moving_sale: false,
    source_lang: 'si',
    created_at: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
  },
  {
    id: 'item-8',
    seller_id: 'user-mn-1',
    seller_name: '울란바토르곰',
    seller_phone: '010-3312-8821',
    seller_country: 'MN',
    seller_country_flag: '🇲🇳',
    title: '🚲 삼천리 21단 하이브리드 출퇴근 자전거 + 전조등/자물쇠 포함',
    description: '구미 공단 통근용으로 타던 자전거입니다. 타이어 펑크 없고 기어 변속 부드럽습니다. 자물쇠랑 LED 전조등 같이 드려요.',
    price: 40000,
    original_price: 220000,
    category: 'vehicles',
    images: [
      'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&auto=format&fit=crop&q=80'
    ],
    region: '구미 국가1산업단지',
    industrial_zone: 'gumi',
    status: 'selling',
    view_count: 115,
    like_count: 22,
    is_moving_sale: false,
    source_lang: 'mn',
    created_at: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
  }
];

export const INITIAL_CHATS: KMarketChat[] = [
  {
    id: 'chat-demo-1',
    item_id: 'item-1',
    item: INITIAL_ITEMS[0],
    buyer_id: 'user-current',
    buyer_name: '나(K-이웃)',
    buyer_country: 'KR',
    buyer_flag: '🇰🇷',
    buyer_lang: 'ko',
    seller_id: 'user-vn-1',
    seller_name: '호치민호랑이',
    seller_country: 'VN',
    seller_flag: '🇻🇳',
    seller_lang: 'vi',
    last_message: 'Vâng, 7 giờ tối nay tại cổng ký túc xá nhé! (네, 오늘 저녁 7시 기숙사 정문에서 봬요!)',
    last_message_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    unread_count: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  }
];
